apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole-certificates.yaml
- clusterrole-challenges.yaml
- clusterrole-clusterissuers.yaml
- clusterrole-ingress-shim.yaml
- clusterrole-issuers.yaml
- clusterrole-orders.yaml
- clusterrolebinding-certificates.yaml
- clusterrolebinding-challenges.yaml
- clusterrolebinding-clusterissuers.yaml
- clusterrolebinding-ingress-shim.yaml
- clusterrolebinding-issuers.yaml
- clusterrolebinding-orders.yaml
