apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - longhorn.yaml
  - limitrange.yaml

configMapGenerator:
  - name: longhorn
    files:
      - config/longhorn/default-setting.yaml

secretGenerator:
  - name: minio
    envs:
    - secrets/minio

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  fluentbit.io/exclude: "true"
