apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - namespace.yaml
  - longhorn

configMapGenerator:
  - name: longhorn
    files:
      - config/longhorn/default-setting.yaml
