{
 "title": "NAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "NAS Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NAS Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (synology_stats_volume_bytes_used / synology_stats_volume_size) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "NAS Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min by (name) (synology_stats_disk_temperature)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "NAS Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "synology_stats_uptime" }
   ]
  }
 ]
}