{
 "title": "Network",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HomeHub Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HomeHub Bytes (Up/Down)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "homehub_stats_bytes_down", "legendFormat": "Down" },
      { "expr": "homehub_stats_bytes_up", "legendFormat": "Up" }
     ]
    },
    {
     "title": "HomeHub Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "homehub_stats_uptime" }
     ]
    }
   ]
  },
  { "title": "Speedtest Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Network Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    { "expr": "network_speed_download", "legendFormat": "Download" },
    { "expr": "network_speed_upload", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_speed_latency" }
   ]
  },
  {
   "title": "World Ping Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "World Ping Times",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "valueName": "current",
     "targets": [
      { "expr": "world_ping_average_rtt", "legendFormat": "{{ country_code }}" }
     ]
    }
   ]
  },
  {
   "title": "PiHole Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "PiHole Ads Blocked",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pihole_summary_ads_blocked" }
     ]
    },
    {
     "title": "PiHole Domains Blocked",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pihole_summary_domains_blocked" }
     ]
    },
    {
     "title": "PiHole Ads Percentage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pihole_summary_ads_percentage" }
     ]
    },
    {
     "title": "PiHole DNS Queries",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pihole_summary_dns_queries_today"
      }
     ]
    }
   ]
  }
 ]
}