route:
  receiver: 'default'
  group_by: ['...']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://alertmanager-discord.homelab.svc.cluster.local:80/webhook'
