apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
spec:
  tls:
  - hosts:
    - photoprism.homelab.dsb.dev
    secretName: photoprism-tls
  rules:
  - host: photoprism.homelab.dsb.dev
    http:
      paths:
      - backend:
          service:
            name: photoprism
            port:
              number: 2342
        path: /
        pathType: Prefix
