group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Expose prometheus metrics.
prometheus:

# Store things in postgres
recorder:
  db_url: !secret db_dsn

# Enable UI
frontend:

# Enable history
history:

# Enable logbook
logbook:

# Enable mobile app
mobile_app:
