group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Expose prometheus metrics.
prometheus:

# Store things in postgres
recorder:
  db_url: !secret db_dsn

# Enable UI
frontend:

# Enable history
history:

# Enable logbook
logbook:

# Enable mobile app
mobile_app:

# Enable system health
system_health:

# Enable spotify integration
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Enable synology DSM integration
synology_dsm:
  - host: 192.168.1.69
    username: !secret synology_username
    password: !secret synology_password

# Enable pihole integration
pi_hole:
  - host: pihole.homelab.dsb.dev:443
    name: Pi-Hole
    ssl: true
    verify_ssl: true
    api_key: !secret pihole_api_key
