apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-csv-importer
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
spec:
  tls:
  - hosts:
    - firefly-csv-importer.homelab.dsb.dev
    secretName: firefly-importer-tls
  rules:
  - host: firefly-csv-importer.homelab.dsb.dev
    http:
      paths:
        - backend:
            service:
              name: firefly-csv-importer
              port:
                number: 8080
          path: /
          pathType: Prefix

