apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
  name: traefik
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 32223
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      nodePort: 31400
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: traefik
  type: LoadBalancer
