apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jetstack-secure-agent-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jetstack-secure-agent-secret-reader
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: jetstack-secure
