apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- cainjector
- cert-manager
- controller
- crd
- issuers
- webhook

secretGenerator:
  - name: cloudflare
    namespace: cert-manager
    envs:
    - secrets/cloudflare

generatorOptions:
  disableNameSuffixHash: true
