apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- limitrange.yaml
- cert-manager.yaml
- issuers

secretGenerator:
  - name: cloudflare
    envs:
    - secrets/cloudflare

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  fluentbit.io/exclude: "true"
