apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- all
- issuers

secretGenerator:
  - name: cloudflare
    namespace: cert-manager
    envs:
    - secrets/cloudflare

generatorOptions:
  disableNameSuffixHash: true
