apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: longhorn-manager
  name: longhorn-manager
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '9500'
    spec:
      containers:
        - name: longhorn-manager
          image: longhornio/longhorn-manager:master
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - longhorn-manager
            - -j
            - daemon
            - --engine-image
            - longhornio/longhorn-engine:master
            - --instance-manager-image
            - longhornio/longhorn-instance-manager:master
            - --manager-image
            - longhornio/longhorn-manager:master
            - --service-account
            - longhorn
          ports:
            - containerPort: 9500
              name: manager
          readinessProbe:
            tcpSocket:
              port: 9500
          volumeMounts:
            - name: dev
              mountPath: /host/dev/
            - name: proc
              mountPath: /host/proc/
            - name: varrun
              mountPath: /var/run/
              mountPropagation: Bidirectional
            - name: longhorn
              mountPath: /var/lib/longhorn/
              mountPropagation: Bidirectional
            - name: longhorn-default-setting
              mountPath: /var/lib/longhorn-setting/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEFAULT_SETTING_PATH
              value: /var/lib/longhorn-setting/default-setting.yaml
      volumes:
        - name: dev
          hostPath:
            path: /dev/
        - name: proc
          hostPath:
            path: /proc/
        - name: varrun
          hostPath:
            path: /var/run/
        - name: longhorn
          hostPath:
            path: /var/lib/longhorn/
        - name: longhorn-default-setting
          configMap:
            name: longhorn
      serviceAccountName: longhorn
      serviceAccount: longhorn
  updateStrategy:
    rollingUpdate:
      maxUnavailable: "100%"
