apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: BackingImageManager
  name: backingimagemanagers.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: BackingImageManager
    listKind: BackingImageManagerList
    plural: backingimagemanagers
    shortNames:
      - lhbim
    singular: backingimagemanager
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: State
          type: string
          description: The current state of the manager
          jsonPath: .status.currentState
        - name: Image
          type: string
          description: The image the manager pod will use
          jsonPath: .spec.image
        - name: Node
          type: string
          description: The node the manager is on
          jsonPath: .spec.nodeID
        - name: DiskUUID
          type: string
          description: The disk the manager is responsible for
          jsonPath: .spec.diskUUID
        - name: DiskPath
          type: string
          description: The disk path the manager is using
          jsonPath: .spec.diskPath
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
