variable "cloudflare_api_key" {}
variable "cloudflare_email" {}
variable "homelab_0_ip" {}
variable "homelab_1_ip" {}
variable "homelab_2_ip" {}
variable "homelab_3_ip" {}
variable "nas_ip" {}
variable "minio_url" {}
variable "minio_access_key" {}
variable "minio_secret_key" {}
