apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- mutatingwebhookconfiguration.yaml
- role.yaml
- rolebinding.yaml
- service.yaml
- serviceaccount.yaml
- validatingwebhookconfiguration.yaml
