apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: directory
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: cloudflare
spec:
  tls:
  - hosts:
    - homelab.dsb.dev
    secretName: directory-tls
  rules:
  - host: homelab.dsb.dev
    http:
      paths:
      - backend:
          service:
            name: directory
            port:
              number: 80
        path: /
        pathType: Prefix
