apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- jaeger
- grafana

configMapGenerator:
- name: grafana
  files:
  - config/grafana.ini

secretGenerator:
- name: grafana
  envs:
  - secrets/grafana
- name: registry
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=secrets/registry
- name: minio
  envs:
  - secrets/minio

patchesStrategicMerge:
- overlays/grafana.yaml
