apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- limitrange.yaml
- jaeger
- grafana
- prometheus
- alertmanager

configMapGenerator:
- name: grafana
  files:
  - config/grafana.ini
- name: prometheus-server
  files:
    - config/prometheus/prometheus.yml
    - config/prometheus/alerting_rules.yml
    - config/prometheus/alerts.yml
    - config/prometheus/recording_rules.yml
    - config/prometheus/rules.yml
- name: alertmanager
  files:
  - config/alertmanager/alertmanager.yaml

secretGenerator:
- name: grafana
  envs:
  - secrets/grafana
- name: registry
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=secrets/registry
- name: minio
  envs:
  - secrets/minio
