apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
        prometheus.io/path: /_prometheus/metrics
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: create
        image: busybox:1.28
        command: ['mkdir', '-p', '/usr/share/elasticsearch/data/nodes/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/plugins
          name: data
          subPath: plugins
      - name: file-permissions
        image: busybox:1.28
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/plugins
          name: data
          subPath: plugins
      containers:
      - name: elasticsearch
        image: elasticsearch:7.10.1
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: data
          - mountPath: /usr/share/elasticsearch/plugins
            name: data
            subPath: plugins
          - name: elasticsearch
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
        readinessProbe:
          timeoutSeconds: 120
          initialDelaySeconds: 120
          httpGet:
            port: 9200
            path: /_cluster/health?wait_for_status=yellow&timeout=120s
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch
        - name: elasticsearch
          configMap:
            name: elasticsearch
