apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 82
      initContainers:
      - name: create
        image: busybox:1.28
        command: ['mkdir', '-p', '/usr/share/elasticsearch/data/nodes/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      - name: file-permissions
        image: busybox:1.28
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      containers:
      - name: elasticsearch
        image: elasticsearch:7.10.1
        env:
          - name: discovery.type
            value: single-node
          - name: bootstrap.memory_lock
            value: "true"
          - name: cluster.name
            value: homelab
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
        readinessProbe:
          timeoutSeconds: 120
          httpGet:
            port: 9200
            path: /_cluster/health?wait_for_status=yellow
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch
