apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
        prometheus.io/path: /_prometheus/metrics
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      # Container creates the directory for node data, for some reason this doesn't just get created automatically
      # by the elasticsearch container.
      - name: create
        image: busybox:1.28
        command: ['mkdir', '-p', '/usr/share/elasticsearch/data/nodes/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/plugins
          name: data
          subPath: plugins
      # Second container sets appropriate permissions for the elasticsearch folder, was experiencing crashes due to
      # fs permissions without doing this.
      - name: file-permissions
        image: busybox:1.28
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/plugins
          name: data
          subPath: plugins
      # Third container removes the prometheus plugin directory if it already exists.
      - name: remove-prometheus-plugin
        image: busybox:1.28
        command: ['rm', '-rf', '/usr/share/elasticsearch/plugins/prometheus-exporter']
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/plugins
            name: data
            subPath: plugins
      # Fourth container installs the prometheus plugin. This will expose prometheus metrics to be scraped.
      - name: install-prometheus-plugin
        image: elasticsearch:7.10.1
        command: ['./bin/elasticsearch-plugin', 'install', '-b', 'https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.10.1.0/prometheus-exporter-7.10.1.0.zip']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/plugins
          name: data
          subPath: plugins
      containers:
      - name: elasticsearch
        image: elasticsearch:7.10.1
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: data
          - mountPath: /usr/share/elasticsearch/plugins
            name: data
            subPath: plugins
          - name: elasticsearch
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
        readinessProbe:
          timeoutSeconds: 120
          initialDelaySeconds: 120
          httpGet:
            port: 9200
            path: /_cluster/health?wait_for_status=yellow&timeout=120s
        resources:
          limits:
            memory: 3Gi
            cpu: "2"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch
        - name: elasticsearch
          configMap:
            name: elasticsearch
