apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn
subjects:
  - kind: ServiceAccount
    name: longhorn
    namespace: longhorn-system
  - kind: ServiceAccount
    name: default
    namespace: longhorn-system
