apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

resources:
- namespace.yaml
- limitrange.yaml
- prometheus-exporters
- minecraft-backup
- directory
- health-dashboard
- alertmanager-discord

secretGenerator:
- name: registry
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=secrets/registry
- name: minio
  envs:
  - secrets/minio
- name: sentry
  envs:
  - secrets/sentry
- name: discord
  envs:
  - secrets/discord

configMapGenerator:
- name: tracing
  envs:
  - config/tracing
- name: prometheus
  envs:
  - config/prometheus
- name: directory
  files:
  - config/directory/config.yaml
