apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

resources:
- namespace.yaml
- prometheus-exporters
- directory

secretGenerator:
- name: registry
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=secrets/registry

configMapGenerator:
- name: tracing
  envs:
  - config/tracing
- name: prometheus
  envs:
  - config/prometheus
- name: directory
  files:
  - config/directory/config.yaml
