apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- coronavirus
- speedtest
- weather
- worldping
- home-assistant
- pihole
- synology

secretGenerator:
- name: weather
  envs:
  - secrets/weather
- name: home-assistant
  envs:
  - secrets/home-assistant
- name: synology
  envs:
  - secrets/synology
