apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities

resources:
- namespace.yaml
- home-assistant
- pihole
- bitwarden
- firefly
- photoprism

configMapGenerator:
- name: tracing
  envs:
  - config/tracing
- name: home-assistant
  files:
  - config/home-assistant/configuration.yaml
  - config/home-assistant/automations.yaml
  - config/home-assistant/scenes.yaml
  - config/home-assistant/scripts.yaml
  - config/home-assistant/groups.yaml
  - config/home-assistant/ui-lovelace.yaml

secretGenerator:
- name: pihole
  envs:
  - secrets/pihole
- name: minio
  envs:
  - secrets/minio
- name: registry
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=secrets/registry
- name: home-assistant
  files:
  - secrets/home-assistant/secrets.yaml
- name: postgres
  envs:
  - secrets/postgres
- name: firefly
  envs:
  - secrets/firefly
- name: photoprism
  envs:
  - secrets/photoprism
