apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole-edit.yaml
- clusterrole-view.yaml
- deployment.yaml
- role.yaml
- rolebinding.yaml
- service.yaml
- serviceaccount.yaml
