{
 "title": "Homelab",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Docker Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Count of running docker services",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_tasks_state{state=\"running\",container_label_com_docker_swarm_service_name=~\".+\"})",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "description": "Memory usage per-container",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Network Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "World Ping Times",
     "type": "grafana-worldmap-panel",
     "description": "Ping times for different servers across the world",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by (country_code) (world_ping_average_rtt)",
       "legendFormat": "{{country_code}}"
      }
     ]
    },
    {
     "title": "Network Latency",
     "type": "gauge",
     "description": "Network latency taken from speedtest.net",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (network_speed_latency)"
      }
     ]
    },
    {
     "title": "Download Speed",
     "type": "gauge",
     "description": "Download speed taken from speedtest.net",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (network_speed_download)",
       "legendFormat": "Download"
      }
     ]
    },
    {
     "title": "Upload Speed",
     "type": "gauge",
     "description": "Upload speed results from speedtest.net",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (network_speed_upload)"
      }
     ]
    },
    {
     "title": "Pihole",
     "type": "stat",
     "description": "Summary data scraped from pihole",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (pihole_summary_ads_blocked)",
       "legendFormat": "Ads Blocked"
      },
      {
       "expr": "avg by (instance) (pihole_summary_domains_blocked)",
       "legendFormat": "Domains Blocked"
      }
     ]
    },
    {
     "title": "Homehub Bytes (Up/Down)",
     "type": "stat",
     "description": "Bytes up/down scraped from the BT home hub",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (homehub_stats_bytes_down)",
       "legendFormat": "Down"
      },
      {
       "expr": "avg by (instance) (homehub_stats_bytes_up)",
       "legendFormat": "Up"
      }
     ]
    },
    {
     "title": "Homehub Uptime",
     "type": "stat",
     "description": "Current uptime of the BT home hub",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (homehub_stats_uptime)",
       "legendFormat": "Seconds"
      }
     ]
    }
   ]
  },
  { "title": "Machine Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Storage",
   "type": "graph",
   "description": "Metrics about the local filesystem",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ((node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"} ) / node_filesystem_size_bytes{mountpoint=\"/\"}  * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Percentage of CPU usage",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[30s]) * 100",
     "legendFormat": "{{instance}} (CPU {{cpu}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Node temperature",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Weather Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Current temperature from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (weather_stats_temperature)",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "description": "Current UV Index",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (weather_stats_uv_index)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "description": "Current humidity from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (weather_stats_humidity)"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "description": "Wind speed result from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (weather_stats_wind_speed)"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "gauge",
   "description": "Precipitation statistics from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (weather_stats_precipitation)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "description": "Pressure statistics from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (weather_stats_pressure)"
    }
   ]
  },
  { "title": "Coronavirus Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Daily Coronavirus Numbers",
   "type": "stat",
   "description": "Daily numbers taken from government coronavirus API",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (coronavirus_stats_case_count)",
     "legendFormat": "Cases"
    },
    {
     "expr": "avg by (instance) (coronavirus_stats_death_count)",
     "legendFormat": "Deaths"
    }
   ]
  }
 ]
}