apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: registry.homelab.dsb.dev/pihole/pihole:v5.3.4
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/London
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole
              key: pihole.password
        # Point DNS to cloudflared for DNS over HTTPS.
        - name: DNS1
          value: 127.0.0.1#5053
        - name: DNS2
          value: ''
        volumeMounts:
        - name: pihole
          mountPath: /etc/pihole
          subPath: pihole
        - name: pihole
          mountPath: /etc/dnsmasq.d
          subPath: dnsmasq
        readinessProbe:
          tcpSocket:
            port: 80
      - name: cloudflared
        image: registry.homelab.dsb.dev/klutchell/cloudflared:2019.12.0
      volumes:
      - name: pihole
        persistentVolumeClaim:
          claimName: pihole
