apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/London
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole
              key: pihole.password
        volumeMounts:
        - name: pihole
          mountPath: /etc/pihole
          subPath: pihole
        - name: pihole
          mountPath: /etc/dnsmasq.d
          subPath: dnsmasq
      volumes:
      - name: pihole
        persistentVolumeClaim:
          claimName: pihole
