apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
spec:
  tls:
  - hosts:
    - pihole.homelab.dsb.dev
    secretName: pihole-tls
  rules:
  - host: pihole.homelab.dsb.dev
    http:
      paths:
      - backend:
          serviceName: pihole
          servicePort: 8000
        path: /

