apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- persistentvolueclaim-dnsmasq.yaml
- persistentvolumeclaim-data.yaml
- ingress.yaml
- ftl-backup-cron.yaml
- gravity-backup-cron.yaml
