apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
spec:
  rules:
    - host: prometheus.homelab
      http:
        paths:
          - backend:
              serviceName: prometheus-server
              servicePort: 80
            path: /
