apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- serviceaccount.yaml
- ingress.yaml
