http:
  middlewares:
    sslheader:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    compression:
        compress:
          excludedContentTypes:
          -  "text/event-stream"
