api:
  insecure: true
  dashboard: true

metrics:
  prometheus:
    entryPoint: metrics

providers:
  file:
    directory: /config/common
  kubernetesIngress: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      middlewares:
        - sslheader@file
  metrics:
    address: :8082
