api:
  insecure: true
  dashboard: true

metrics:
  prometheus:
    entryPoint: metrics

providers:
  file:
    directory: /config/common
  kubernetesIngress: {}

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      middlewares:
        - sslheader@file
  metrics:
    address: :8081
  ping:
    address: :8082

ping:
  entryPoint: ping
