server: "https://platform.jetstack.io"
organization_id: "romantic-shannon"
cluster_id: "homelab"
data-gatherers:
# pods data is used in the pods and application_versions packages
- kind: "k8s-dynamic"
  name: "k8s/pods"
  config:
    resource-type:
      resource: pods
      version: v1
# gather services for pod readiness probe rules
- kind: "k8s-dynamic"
  name: "k8s/services"
  config:
    resource-type:
      resource: services
      version: v1
# gather higher level resources to ensure data to determine ownership is present
- kind: "k8s-dynamic"
  name: "k8s/deployments"
  config:
    resource-type:
      version: v1
      resource: deployments
      group: apps
- kind: "k8s-dynamic"
  name: "k8s/replicasets"
  config:
    resource-type:
      version: v1
      resource: replicasets
      group: apps
- kind: "k8s-dynamic"
  name: "k8s/statefulsets"
  config:
    resource-type:
      version: v1
      resource: statefulsets
      group: apps
- kind: "k8s-dynamic"
  name: "k8s/daemonsets"
  config:
    resource-type:
      version: v1
      resource: daemonsets
      group: apps
- kind: "k8s-dynamic"
  name: "k8s/jobs"
  config:
    resource-type:
      version: v1
      resource: jobs
      group: batch
- kind: "k8s-dynamic"
  name: "k8s/cronjobs"
  config:
    resource-type:
      version: v1beta1
      resource: cronjobs
      group: batch
# gather resources for cert-manager package
- kind: "k8s-dynamic"
  name: "k8s/secrets"
  config:
    resource-type:
      version: v1
      resource: secrets
- kind: "k8s-dynamic"
  name: "k8s/certificates"
  config:
    resource-type:
      group: cert-manager.io
      version: v1
      resource: certificates
- kind: "k8s-dynamic"
  name: "k8s/ingresses"
  config:
    resource-type:
      group: networking.k8s.io
      version: v1beta1
      resource: ingresses
- kind: "k8s-dynamic"
  name: "k8s/certificaterequests"
  config:
    resource-type:
      group: cert-manager.io
      version: v1
      resource: certificaterequests
- kind: "k8s-dynamic"
  name: "k8s/issuers"
  config:
    resource-type:
      group: cert-manager.io
      version: v1
      resource: issuers
- kind: "k8s-dynamic"
  name: "k8s/clusterissuers"
  config:
    resource-type:
      group: cert-manager.io
      version: v1
      resource: clusterissuers
- kind: "k8s-dynamic"
  name: "k8s/mutatingwebhookconfigurations"
  config:
    resource-type:
      group: admissionregistration.k8s.io
      version: v1
      resource: mutatingwebhookconfigurations
- kind: "k8s-dynamic"
  name: "k8s/validatingwebhookconfigurations"
  config:
    resource-type:
      group: admissionregistration.k8s.io
      version: v1
      resource: validatingwebhookconfigurations
