{
 "title": "Homelab",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Weather Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Current temperature from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_stats_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "description": "Current UV Index",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_stats_uv_index" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "description": "Current humidity from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_stats_humidity" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "description": "Wind speed result from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_stats_wind_speed" }
   ]
  },
  {
   "title": "Precipitation",
   "type": "gauge",
   "description": "Precipitation statistics from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_stats_precipitation" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "description": "Pressure statistics from weatherapi.com",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_stats_pressure" }
   ]
  },
  { "title": "Network Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Network Latency",
   "type": "gauge",
   "description": "Network latency taken from speedtest.net",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_speed_latency" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "description": "Download speed taken from speedtest.net",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_speed_download", "legendFormat": "Download" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "description": "Upload speed results from speedtest.net",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_speed_upload" }
   ]
  },
  {
   "title": "Pihole",
   "type": "stat",
   "description": "Summary data scraped from pihole",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_summary_ads_blocked", "legendFormat": "Ads Blocked" },
    { "expr": "pihole_summary_domains_blocked", "legendFormat": "Domains Blocked" }
   ]
  },
  { "title": "Machine Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Metrics about the local filesystem",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Memory usage",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "Used" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_Active_bytes",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Coronavirus Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Daily Coronavirus Numbers",
   "type": "stat",
   "description": "Daily numbers taken from government coronavirus API",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coronavirus_stats_case_count", "legendFormat": "Cases" },
    { "expr": "coronavirus_stats_death_count", "legendFormat": "Deaths" }
   ]
  }
 ]
}