apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - system-upgrade-controller
  - traefik
  - cert-manager

configMapGenerator:
  - name: traefik
    files:
      - config/traefik.toml

secretGenerator:
  - name: traefik
    files:
      - secrets/traefik/tls.crt
      - secrets/traefik/tls.key
