apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - system-upgrade-controller
  - traefik

secretGenerator:
  - name: traefik
    envs:
    - secrets/traefik
