apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system
spec:
  limits:
    - default:
        memory: 1Gi
        cpu: "1"
      defaultRequest:
        memory: 128Mi
        cpu: 100m
      type: Container
