apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: davidsbond93@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-cloudflare
    solvers:
      - dns01:
          cloudflare:
            email: davidsbond93@gmail.com
            apiTokenSecretRef:
              name: cloudflare
              key: api.token
